// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/liveness.proto

package liveness

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Liveness_LivenessRPC_FullMethodName = "/lerpc.Liveness/LivenessRPC"
)

// LivenessClient is the client API for Liveness service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivenessClient interface {
	LivenessRPC(ctx context.Context, in *LivenessMessage, opts ...grpc.CallOption) (*LivenessMessage, error)
}

type livenessClient struct {
	cc grpc.ClientConnInterface
}

func NewLivenessClient(cc grpc.ClientConnInterface) LivenessClient {
	return &livenessClient{cc}
}

func (c *livenessClient) LivenessRPC(ctx context.Context, in *LivenessMessage, opts ...grpc.CallOption) (*LivenessMessage, error) {
	out := new(LivenessMessage)
	err := c.cc.Invoke(ctx, Liveness_LivenessRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivenessServer is the server API for Liveness service.
// All implementations must embed UnimplementedLivenessServer
// for forward compatibility
type LivenessServer interface {
	LivenessRPC(context.Context, *LivenessMessage) (*LivenessMessage, error)
	mustEmbedUnimplementedLivenessServer()
}

// UnimplementedLivenessServer must be embedded to have forward compatible implementations.
type UnimplementedLivenessServer struct {
}

func (UnimplementedLivenessServer) LivenessRPC(context.Context, *LivenessMessage) (*LivenessMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LivenessRPC not implemented")
}
func (UnimplementedLivenessServer) mustEmbedUnimplementedLivenessServer() {}

// UnsafeLivenessServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivenessServer will
// result in compilation errors.
type UnsafeLivenessServer interface {
	mustEmbedUnimplementedLivenessServer()
}

func RegisterLivenessServer(s grpc.ServiceRegistrar, srv LivenessServer) {
	s.RegisterService(&Liveness_ServiceDesc, srv)
}

func _Liveness_LivenessRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivenessServer).LivenessRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Liveness_LivenessRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivenessServer).LivenessRPC(ctx, req.(*LivenessMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// Liveness_ServiceDesc is the grpc.ServiceDesc for Liveness service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Liveness_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lerpc.Liveness",
	HandlerType: (*LivenessServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LivenessRPC",
			Handler:    _Liveness_LivenessRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/liveness.proto",
}
