// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: proto/liveness.proto

package liveness

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LivenessService_LivenessRPC_FullMethodName = "/lerpc.LivenessService/LivenessRPC"
)

// LivenessServiceClient is the client API for LivenessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LivenessServiceClient interface {
	LivenessRPC(ctx context.Context, in *Liveness, opts ...grpc.CallOption) (*Liveness, error)
}

type livenessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLivenessServiceClient(cc grpc.ClientConnInterface) LivenessServiceClient {
	return &livenessServiceClient{cc}
}

func (c *livenessServiceClient) LivenessRPC(ctx context.Context, in *Liveness, opts ...grpc.CallOption) (*Liveness, error) {
	out := new(Liveness)
	err := c.cc.Invoke(ctx, LivenessService_LivenessRPC_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LivenessServiceServer is the server API for LivenessService service.
// All implementations must embed UnimplementedLivenessServiceServer
// for forward compatibility
type LivenessServiceServer interface {
	LivenessRPC(context.Context, *Liveness) (*Liveness, error)
	mustEmbedUnimplementedLivenessServiceServer()
}

// UnimplementedLivenessServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLivenessServiceServer struct {
}

func (UnimplementedLivenessServiceServer) LivenessRPC(context.Context, *Liveness) (*Liveness, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LivenessRPC not implemented")
}
func (UnimplementedLivenessServiceServer) mustEmbedUnimplementedLivenessServiceServer() {}

// UnsafeLivenessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LivenessServiceServer will
// result in compilation errors.
type UnsafeLivenessServiceServer interface {
	mustEmbedUnimplementedLivenessServiceServer()
}

func RegisterLivenessServiceServer(s grpc.ServiceRegistrar, srv LivenessServiceServer) {
	s.RegisterService(&LivenessService_ServiceDesc, srv)
}

func _LivenessService_LivenessRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Liveness)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LivenessServiceServer).LivenessRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LivenessService_LivenessRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LivenessServiceServer).LivenessRPC(ctx, req.(*Liveness))
	}
	return interceptor(ctx, in, info, handler)
}

// LivenessService_ServiceDesc is the grpc.ServiceDesc for LivenessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LivenessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lerpc.LivenessService",
	HandlerType: (*LivenessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LivenessRPC",
			Handler:    _LivenessService_LivenessRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/liveness.proto",
}
