// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: proto/proposal.proto

package proposal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Proposal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VersionTag uint64           `protobuf:"varint,1,opt,name=VersionTag,proto3" json:"VersionTag,omitempty"`
	Proposer   []byte           `protobuf:"bytes,2,opt,name=Proposer,proto3" json:"Proposer,omitempty"`
	Payload    *ProposalPayload `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
}

func (x *Proposal) Reset() {
	*x = Proposal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proposal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Proposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proposal) ProtoMessage() {}

func (x *Proposal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proposal.ProtoReflect.Descriptor instead.
func (*Proposal) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{0}
}

func (x *Proposal) GetVersionTag() uint64 {
	if x != nil {
		return x.VersionTag
	}
	return 0
}

func (x *Proposal) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *Proposal) GetPayload() *ProposalPayload {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ProposalPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation     string `protobuf:"bytes,1,opt,name=Operation,proto3" json:"Operation,omitempty"`
	ModifiedState []byte `protobuf:"bytes,2,opt,name=ModifiedState,proto3" json:"ModifiedState,omitempty"`
}

func (x *ProposalPayload) Reset() {
	*x = ProposalPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_proposal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalPayload) ProtoMessage() {}

func (x *ProposalPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proposal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalPayload.ProtoReflect.Descriptor instead.
func (*ProposalPayload) Descriptor() ([]byte, []int) {
	return file_proto_proposal_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalPayload) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ProposalPayload) GetModifiedState() []byte {
	if x != nil {
		return x.ModifiedState
	}
	return nil
}

var File_proto_proposal_proto protoreflect.FileDescriptor

var file_proto_proposal_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x22, 0x78, 0x0a,
	0x08, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x12, 0x30, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x55, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x61, 0x6c, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x32, 0x44,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x31, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x52, 0x50, 0x43,
	0x12, 0x0f, 0x2e, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x1a, 0x0f, 0x2e, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73,
	0x61, 0x6c, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x70, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_proposal_proto_rawDescOnce sync.Once
	file_proto_proposal_proto_rawDescData = file_proto_proposal_proto_rawDesc
)

func file_proto_proposal_proto_rawDescGZIP() []byte {
	file_proto_proposal_proto_rawDescOnce.Do(func() {
		file_proto_proposal_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_proposal_proto_rawDescData)
	})
	return file_proto_proposal_proto_rawDescData
}

var file_proto_proposal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_proposal_proto_goTypes = []interface{}{
	(*Proposal)(nil),        // 0: lerpc.Proposal
	(*ProposalPayload)(nil), // 1: lerpc.ProposalPayload
}
var file_proto_proposal_proto_depIdxs = []int32{
	1, // 0: lerpc.Proposal.Payload:type_name -> lerpc.ProposalPayload
	0, // 1: lerpc.ProposalService.ProposalRPC:input_type -> lerpc.Proposal
	0, // 2: lerpc.ProposalService.ProposalRPC:output_type -> lerpc.Proposal
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_proposal_proto_init() }
func file_proto_proposal_proto_init() {
	if File_proto_proposal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_proposal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Proposal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_proposal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_proposal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proposal_proto_goTypes,
		DependencyIndexes: file_proto_proposal_proto_depIdxs,
		MessageInfos:      file_proto_proposal_proto_msgTypes,
	}.Build()
	File_proto_proposal_proto = out.File
	file_proto_proposal_proto_rawDesc = nil
	file_proto_proposal_proto_goTypes = nil
	file_proto_proposal_proto_depIdxs = nil
}
